---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
spec:
  replicas: 1
  minReadySeconds: 10 # wait for 10 sec before going to deploy next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1        # max number of pods to run for the deployment
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      imagePullSecrets:
       - name: docker-reg
      containers:
       - name: myapp
         image: 131270908001.dkr.ecr.us-east-1.amazonaws.com/go-app-repo:latest
         imagePullPolicy: Always 
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myloadbalancer
  labels:
    app: myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: myapp

