################################
##  CONFIGURATION             ##
################################

variables:
  DOCKER_TLS_CERTDIR: ""


.install_awscli: &install_awscli |
  apk add --no-cache curl jq python3 py-pip
  pip install awscli --upgrade

################################
##  CI/CD PIPELINE            ##
################################

stages:
- build
# - test
# - "deploy to EKS"

build-image:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - *install_awscli
    - aws --version
    - docker --version
  script:
  - echo ${CI_COMMIT_REF_NAME} > VERSION
  - export VERSION_TAG_K8s=$(echo ${CI_COMMIT_REF_NAME}_$(date +%Y%m%d_%H%M%S) | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]._-')
  - export VERSION_IMAGE_K8S=${ECR_REPOSITORY}:${VERSION_TAG_K8s}
  - echo ${VERSION_IMAGE_K8S}
  - aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
  - docker pull ${ECR_REPOSITORY}:latest || true
  - docker build -t ${VERSION_IMAGE_K8S} -t ${ECR_REPOSITORY}:latest -f ." .
  - docker push ${VERSION_IMAGE_K8S}
  - docker push ${ECR_REPOSITORY}:latest
  - echo "DEPLOY_VERSION=${VERSION_TAG_K8s}" >> image.env
  - echo "VERSION_IMAGE_K8S=${VERSION_IMAGE_K8S}" >> image.env
  - cat image.env
  artifacts:
    reports:
      dotenv: image.env
  rules:
  - when: always

