################################
##  CONFIGURATION             ##
################################

variables:
  DOCKER_TLS_CERTDIR: ""
  CLUSTER_NAME: "test-cluster-SucEGSlU"


.install_awscli: &install_awscli |
  apk add --no-cache curl python3
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  python3 get-pip.py pip==21.1.1
  pip install awscli --upgrade

.kubectl_config: &kubectl_config
- aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${CLUSTER_NAME}

################################
##  CI/CD PIPELINE            ##
################################

stages:
- test
- build
- deploy


build-and-test-app:
  stage: test
  image: golang:alpine
  before_script:
    - apk add bash ca-certificates git gcc g++ libc-dev make
    - go version
  script:
  - make build
  rules:
  - when: always

build-image:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - *install_awscli
    - aws --version
    - docker --version
  script:
  - echo ${CI_COMMIT_REF_NAME} > VERSION
  - export VERSION_TAG_K8s=$(echo ${CI_COMMIT_REF_NAME}_$(date +%Y%m%d_%H%M%S) | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]._-')
  - export VERSION_IMAGE_K8S=${ECR_REPOSITORY}:${VERSION_TAG_K8s}
  - echo ${VERSION_IMAGE_K8S}
  - aws ecr get-login-password | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
  - docker pull ${ECR_REPOSITORY}:latest || true
  - docker build -t ${VERSION_IMAGE_K8S} -t ${ECR_REPOSITORY}:latest .
  - docker push ${VERSION_IMAGE_K8S}
  - docker push ${ECR_REPOSITORY}:latest
  - echo "DEPLOY_VERSION=${VERSION_TAG_K8s}" >> image.env
  - echo "VERSION_IMAGE_K8S=${VERSION_IMAGE_K8S}" >> image.env
  - cat image.env
  artifacts:
    paths: 
      - image.env
  rules:
  - when: always


deploy-to-k8s-cluster:
  image: alpine/k8s:1.19.15
  stage: deploy
  before_script:
  - *install_awscli
  - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
  - chmod +x ./aws-iam-authenticator
  - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
  - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - aws-iam-authenticator help
  - *kubectl_config
  - cat /root/.kube/config
  - aws s3 ls
  script:
    - source image.env
    - sed -i "s|ECR_REPO_IMAGE|${VERSION_IMAGE_K8S}|g" deployment.yml
    - kubectl apply -f deployment.yaml
  only:
    - main
