---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: sample-go-app
  template:
    metadata:
      labels:
        name: sample-go-app
    spec:
      containers:
      - name: application
        image: ECR_REPO_IMAGE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
