---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sample-go-app
  template:
    metadata:
      labels:
        name: sample-go-app
    spec:
      containers:
      - name: application
        image: 944365771232.dkr.ecr.us-west-2.amazonaws.com/go-app-repo:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
